"""Add ZSSPD models

Revision ID: 555c66b53bed
Revises: cc26e14c1fab
Create Date: 2026-01-16 06:31:56.052496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555c66b53bed'
down_revision: Union[str, None] = 'cc26e14c1fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zsspd_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('INCOMING', 'OUTGOING', name='zsspddirection'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'EXPORTED', 'SENT', 'RECEIVED', 'DISTRIBUTED', 'ARCHIVED', name='zsspdstatus'), nullable=False),
    sa.Column('external_sender', sa.String(length=255), nullable=True),
    sa.Column('external_recipient', sa.String(length=255), nullable=True),
    sa.Column('outgoing_number', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zsspd_packages_id'), 'zsspd_packages', ['id'], unique=False)
    op.create_table('zsspd_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['zsspd_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zsspd_files_id'), 'zsspd_files', ['id'], unique=False)
    op.create_table('zsspd_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['zsspd_packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zsspd_recipients_id'), 'zsspd_recipients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zsspd_recipients_id'), table_name='zsspd_recipients')
    op.drop_table('zsspd_recipients')
    op.drop_index(op.f('ix_zsspd_files_id'), table_name='zsspd_files')
    op.drop_table('zsspd_files')
    op.drop_index(op.f('ix_zsspd_packages_id'), table_name='zsspd_packages')
    op.drop_table('zsspd_packages')
    # ### end Alembic commands ###
