"""add message to channel invitations

Revision ID: add_message_to_channel_invitations
Revises: ec814d867c58
Create Date: 2025-01-24 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_message_to_channel_invitations'
down_revision = 'ec814d867c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_invitations', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_invitations', 'message')
    # ### end Alembic commands ###